from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from star_chart.cli import main
from star_chart.github_api import load_fixture
from star_chart.render import ChartOptions, render_svg
from star_chart.themes import THEMES, palette


ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "creatorhub.json"


class RenderTests(unittest.TestCase):
    def test_all_theme_and_style_combinations_render(self) -> None:
        data = load_fixture(str(FIXTURE))
        for theme in THEMES:
            for style in ("card", "minimal", "glass", "neon"):
                svg = render_svg(data, palette(theme, "dark"), "dark", ChartOptions(style=style))
                self.assertTrue(svg.startswith("<svg"))
                self.assertIn("30 stars", svg)
                self.assertIn("3441293738/creatorhub", svg)
                self.assertNotIn("GITHUB_TOKEN", svg)

    def test_cli_writes_light_and_dark(self) -> None:
        with tempfile.TemporaryDirectory() as folder:
            code = main(["--fixture", str(FIXTURE), "--output-dir", folder, "--theme", "creatorhub"])
            self.assertEqual(code, 0)
            for filename in ("star-history.svg", "star-history-dark.svg"):
                target = Path(folder) / filename
                self.assertTrue(target.is_file())
                self.assertIn("generated by github-star-chart", target.read_text("utf-8"))

    def test_custom_accent(self) -> None:
        custom = palette("github", "light", "#123456", "#abcdef")
        self.assertEqual(custom.accent, "#123456")
        self.assertEqual(custom.accent_2, "#abcdef")

    def test_rejects_svg_attribute_in_color(self) -> None:
        with self.assertRaises(ValueError):
            palette("github", "light", '#fff" onload="alert(1)')


if __name__ == "__main__":
    unittest.main()
